# Generated by Django 5.2.14 on 2026-05-23 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "ordering": ["order", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("short_description", models.CharField(max_length=240)),
                ("description", models.TextField()),
                ("github_url", models.URLField(blank=True)),
                ("live_url", models.URLField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="projects/thumbnails/"),
                ),
                ("video_demo", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "tech_stack",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="portfolio.techstack"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="projects.projecttag"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("image", models.ImageField(blank=True, upload_to="projects/gallery/")),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-id"],
                "abstract": False,
            },
        ),
    ]
