# Generated by Django 5.2.14 on 2026-05-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("company", models.CharField(max_length=120)),
                ("role", models.CharField(max_length=120)),
                ("duration", models.CharField(max_length=120)),
                ("responsibilities", models.TextField()),
                (
                    "tech_used",
                    models.ManyToManyField(
                        blank=True, related_name="experiences", to="portfolio.techstack"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-id"],
                "abstract": False,
            },
        ),
    ]
