# Generated by Django 5.2.14 on 2026-05-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("institution", models.CharField(max_length=150)),
                ("degree", models.CharField(max_length=150)),
                ("year", models.CharField(max_length=30)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["order", "-id"],
                "abstract": False,
            },
        ),
    ]
