# Generated by Django 5.2.14 on 2026-05-23 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("role", models.CharField(max_length=120)),
                ("tagline", models.CharField(max_length=255)),
                ("biography", models.TextField(blank=True)),
                ("experience_summary", models.TextField(blank=True)),
                ("skills_summary", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("is_available", models.BooleanField(default=True)),
                ("resume", models.FileField(blank=True, upload_to="resume/")),
                ("profile_image", models.ImageField(blank=True, upload_to="profile/")),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("platform", models.CharField(max_length=50)),
                ("url", models.URLField()),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "ordering": ["order", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TechCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["order", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=120)),
                ("level", models.PositiveSmallIntegerField(default=80)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="portfolio.techcategory",
                    ),
                ),
            ],
            options={
                "unique_together": {("category", "name")},
            },
        ),
    ]
