# Generated by Django 5.2.14 on 2026-05-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=150)),
                ("issuer", models.CharField(max_length=150)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("credential_url", models.URLField(blank=True)),
                (
                    "preview_image",
                    models.ImageField(blank=True, upload_to="certifications/"),
                ),
            ],
            options={
                "ordering": ["order", "-id"],
                "abstract": False,
            },
        ),
    ]
